### ISSUE TITLE
Argument splatting

### ISSUE THREAD

**Issue by casey** [soenkehahn/stir#24]
It might be interesting to support a splat operator, so if you have a vector of strings, you can provide them as arguments to `cmd!`:

```rust
let files = &["a", "b", "c"];
cmd!("cat", *files);
```

Annoyingly, `*` is an operator in Rust, so that might be ambiguous. Maybe `...` would work:

```rust
let files = &["a", "b", "c"];
cmd!("cat", files...);
```

(This is not super obvious, but it's similar to variadic generics in C++.)

**Comment by soenkehahn** [comment]
What should already work (after #27) is this:

``` rust
let files = &["a", "b", "c"];
let contents: String = cmd!("cat", files);
```

Which would result in `cmd a b c`. Is that what you're after with this issue? Or am I misunderstanding this?

**Comment by casey** [comment]
I think I misunderstood that this would work without any special effort.
